# Generated by Django 5.1.3 on 2024-11-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ms_kiersten", "0002_blogpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="post_published_date",
        ),
    ]
