# Generated by Django 5.1.3 on 2024-11-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ms_kiersten", "0004_bloglist_alter_albumpage_album_art"),
    ]

    operations = [
        migrations.RenameField(
            model_name="albumpage",
            old_name="album_art",
            new_name="album_cover_image",
        ),
    ]
