# Generated by Django 5.1.3 on 2024-11-29 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ms_kiersten", "0005_rename_album_art_albumpage_album_cover_image"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="albumpage",
            name="album_streaming_link",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="albumpage",
            name="album_cover_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
