# Generated by Django 5.1.3 on 2024-11-30 12:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ms_kiersten", "0006_albumpage_album_streaming_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloglist",
            name="blog_headline",
            field=wagtail.fields.RichTextField(default="Lorem ipsum"),
            preserve_default=False,
        ),
    ]
