# Generated by Django 5.1.3 on 2024-12-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ms_kiersten", "0008_alter_blogpost_post_cover_image"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="post_cover_image"
        ),
        migrations.AddField(
            model_name="blogpost",
            name="post_cover_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
