# Generated by Django 5.1.3 on 2024-11-10 13:52

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="headline",
            field=wagtail.fields.RichTextField(
                default="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut viverra suscipit est, non blandit ligula. Mauris sagittis magna dolor, nec."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
    ]
