# Generated by Django 5.1.3 on 2024-11-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_homepagemenulink"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepagemenulink",
            name="url",
        ),
        migrations.AddField(
            model_name="homepagemenulink",
            name="external_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="homepagemenulink",
            name="page_link",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.page",
            ),
        ),
    ]
