# Generated by Django 5.1.3 on 2024-11-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_homepagemenulink_external_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagemenulink",
            name="external_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
