# Generated by Django 5.1.11 on 2025-08-08 15:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_photogalleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photogalleryimage",
            name="caption",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
